# ---------------------------------------------------------------------
# skillet preamble information used by panhandler
# unique snippet name
name: 3GPPRA_Gp_ROAMv001
# label used for menu selection
label: 3GPP RefArch PanOS Skillet for Gp between SGSN and GGSN  accross the GRX
description: Reference Architecture for 3GPP Reference Point Gp between legacy SGSN and GGSN. Provides IP+App-ID level protection, GTP stateful inspection, GTP MEssage Type Filter and selected GTP Messages Flooding Filter.
type: panos
extends:
labels:
  collection:
    - 3GPPRefArch__ROAM
# end of preamble section
# ---------------------------------------------------------------------
# variables section
#
variables:
#
# ---------------------------------------------------------------------
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
#
