# ---------------------------------------------------------------------
# skillet preamble information used by panhandler
# unique snippet name
name: 3GPPRA_S10_EPCv001
# label used for menu selection
label: 3GPP RefArch PanOS Skillet for S10 between MMEs
description: Reference Architecture for 3GPP Reference Point S10 between MMEs for Handover and relocation procedures. Provides IP+App-ID level protection, GTP stateful inspection, GTP Message Type Filtering and selected GTP Messages Flooding Filter.  
type: panos
extends:
labels:
  collection:
    - 3GPPRefArch__EPC
# end of preamble section
# ---------------------------------------------------------------------
# variables section
#
variables:
#
# ---------------------------------------------------------------------
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
#
